name: Increment Patch

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
      
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
          fetch-depth: 0 # this is required to see all branches
    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      run: |
        npm install semver
        npm install fs
    - name: Increment version
      run: |
        echo "Incrementing version..."
        VERSION=$(cat VERSION)
        NEW_VERSION=$(node -p "require('semver').inc('$VERSION', 'patch')")
        echo "v$NEW_VERSION" > VERSION
        echo "NEW_VERSION=$NEW_VERSION" >> "$GITHUB_ENV"
        echo "New version is $NEW_VERSION"
    - name: Commit and push
      run: |
        git checkout -b update-version-${{ env.NEW_VERSION }}
        git add VERSION
        git commit -m "Increment version to ${{ env.NEW_VERSION }}"
        git push
        gh pr create --title "Automatic version increment ${{ env.NEW_VERSION }}" --body "This is an automated PR to increment the version."
