name: Build Template

on: [push, pull_request, workflow_dispatch, schedule]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.number || github.sha }}
  cancel-in-progress: true

env:
  CLICKHOUSE_TEST_VERSIONS: "[]"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        clickhouse: ${{CLICKHOUSE_TEST_VERSIONS}}
    name: ClickHouse ${{ matrix.clickhouse }} tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        env:
          CLICKHOUSE_VERSION: ${{ matrix.clickhouse }}
        with:
          arguments: test
