name: Build Against ClickHouse Head

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.number || github.sha }}
  cancel-in-progress: true

env:
  CLICKHOUSE_TEST_VERSIONS: '["head"]'

extends:
  - .github/workflow/test-template.yml

